# Use official PostgreSQL image
FROM postgres:14-alpine

# Set environment variables for DB setup
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=tasks_db

# Expose PostgreSQL port
EXPOSE 5432
